import {
  Activity,
  AppWindow,
  Apple,
  Armchair,
  Beer,
  Bike,
  BookOpen,
  Bot,
  Brain,
  Briefcase,
  CheckCircle2,
  Coffee,
  Dumbbell,
  Eye,
  Flame,
  Gamepad2,
  Ghost,
  GraduationCap,
  Headphones,
  Heart,
  Lightbulb,
  Link,
  Lock,
  Monitor,
  Moon,
  MoonStar,
  MoveVertical,
  PenTool,
  Pill,
  Plane,
  Shield,
  ShoppingBag,
  Smile,
  Sparkles,
  Smartphone,
  Star,
  Stethoscope,
  Target,
  Truck,
  User,
  Wind,
  Zap,
} from "lucide-react";

import type { ActionId, QuestDefinition, StatKey } from "@/types/game";

const BASE_RATE = 0.0025;
const SUB_RATE = 0.001;
export const STATS_DEF = {
  health: { label: "체력", color: "text-red-500", bg: "bg-red-500", stroke: "#ef4444", icon: Heart },
  intelligence: { label: "지능", color: "text-blue-500", bg: "bg-blue-500", stroke: "#3b82f6", icon: Brain },
  focus: { label: "집중", color: "text-purple-500", bg: "bg-purple-500", stroke: "#a855f7", icon: Target },
  immunity: { label: "면역", color: "text-green-500", bg: "bg-green-500", stroke: "#22c55e", icon: Shield },
  eq: { label: "정서", color: "text-pink-500", bg: "bg-pink-500", stroke: "#ec4899", icon: Smile },
  willpower: { label: "의지", color: "text-orange-500", bg: "bg-orange-500", stroke: "#f97316", icon: Flame },
} as const;

export const WORK_COST = {
  physical: {
    health: -0.0015,
    immunity: -0.001,
    willpower: -0.0003,
  },
  mental: {
    willpower: -0.0015,
    focus: -0.001,
    health: -0.0002,
  },
  light: {
    health: -0.0007,
    willpower: -0.0005,
  },
} as const;

export const INDUSTRIES = {
  office: { id: "office", label: "사무/관리", icon: Briefcase, core: ["intelligence", "willpower"] as const, baseWage: 20, desc: "지능과 끈기가 필요한 관리직." },
  dev: { id: "dev", label: "개발/기술", icon: CheckCircle2, core: ["intelligence", "focus"] as const, baseWage: 28, desc: "높은 지능과 집중력이 필수." },
  sales: { id: "sales", label: "영업/마케팅", icon: Target, core: ["eq", "willpower"] as const, baseWage: 22, desc: "정서 지능과 의지가 중요." },
  logistics: { id: "logistics", label: "생산/물류", icon: Truck, core: ["health", "immunity"] as const, baseWage: 18, desc: "강인한 신체 능력이 자산." },
  fitness: { id: "fitness", label: "헬스/피트니스", icon: Activity, core: ["health", "focus"] as const, baseWage: 24, desc: "체력과 집중력이 요구됨." },
  pro: { id: "pro", label: "전문직", icon: Stethoscope, core: ["intelligence", "eq"] as const, baseWage: 45, desc: "지능과 정서적 안정이 모두 필요." },
} as const;

export const COMPANY_TIERS = [
  { id: "sme", label: "중소기업", minStat: 20, mult: 1, color: "text-gray-600" },
  { id: "mid", label: "중견기업", minStat: 50, mult: 1.3, color: "text-blue-600" },
  { id: "enterprise", label: "대기업", minStat: 90, mult: 1.8, color: "text-indigo-600" },
  { id: "global", label: "글로벌", minStat: 140, mult: 2.5, color: "text-purple-600" },
] as const;

export const POSITIONS = [
  { id: "entry", label: "사원", addStat: 0, mult: 1 },
  { id: "junior", label: "주임", addStat: 10, mult: 1.1 },
  { id: "assistant", label: "대리", addStat: 20, mult: 1.3 },
  { id: "manager", label: "과장", addStat: 30, mult: 1.6 },
  { id: "deputy", label: "차장", addStat: 40, mult: 2 },
  { id: "senior", label: "부장", addStat: 50, mult: 2.5 },
  { id: "director", label: "이사", addStat: 70, mult: 3 },
  { id: "executive", label: "임원", addStat: 90, mult: 4 },
  { id: "ceo", label: "CEO", addStat: 110, mult: 6 },
] as const;

export const PART_TIME_JOBS = [
  { id: "convenience", label: "편의점 알바", wage: 15, req: {}, desc: "가장 기본적인 아르바이트.", icon: ShoppingBag },
  { id: "restaurant", label: "식당 서빙", wage: 17, req: { health: 20 }, desc: "기초 체력이 필요합니다.", icon: Coffee },
  { id: "cleaning", label: "청소 용역", wage: 20, req: { health: 30, immunity: 20 }, desc: "힘들지만 시급이 괜찮습니다.", icon: User },
  { id: "delivery_rent", label: "배달 (도보/렌트)", wage: 18, req: { health: 25 }, desc: "맨몸으로 뛰는 배달.", icon: User },
  { id: "delivery_bike", label: "배달 (자전거)", wage: 23, req: { item: "budget_courier_bike" }, desc: "자전거로 배달합니다.", icon: Bike },
  { id: "delivery_own", label: "배달 (오토바이)", wage: 28, req: { item: "bike" }, desc: "오토바이 보유 시 고수익.", icon: Zap },
  { id: "moving", label: "이삿짐 센터", wage: 35, req: { health: 50, immunity: 40 }, desc: "강인한 체력 필수.", icon: Truck },
  { id: "tutor_part", label: "대학생 과외", wage: 40, req: { intelligence: 50 }, desc: "지식을 파는 고소득 알바.", icon: BookOpen },
] as const;

export const ACTIONS = {
  study: { id: "study", label: "공부", icon: BookOpen, desc: "지능 +0.0025/s", multipliers: { intelligence: BASE_RATE, focus: SUB_RATE, willpower: SUB_RATE }, moneyGain: 0 },
  reading: { id: "reading", label: "독서", icon: BookOpen, desc: "지능 +0.0025/s, 정서 +0.0025/s", multipliers: { intelligence: BASE_RATE, eq: BASE_RATE, focus: SUB_RATE }, moneyGain: 0 },
  exercise: { id: "exercise", label: "운동", icon: Activity, desc: "체력 +0.0025/s, 면역 +0.0025/s", multipliers: { health: BASE_RATE, immunity: BASE_RATE, willpower: SUB_RATE }, moneyGain: 0 },
  meditation: { id: "meditation", label: "명상", icon: Brain, desc: "집중 +0.0025/s, 정서 +0.0025/s", multipliers: { focus: BASE_RATE, eq: BASE_RATE, willpower: SUB_RATE }, moneyGain: 0 },
  work: {
    id: "work",
    label: "몰입 작업(근로)",
    icon: Briefcase,
    desc: "현재 직장/알바 수익 창출 (체력/멘탈 소모)",
    multipliers: {},
    moneyGain: "dynamic" as const,
  },
  rest: { id: "rest", label: "휴식", icon: Coffee, desc: "정서 회복, 체력 보존", multipliers: { eq: BASE_RATE, immunity: SUB_RATE, health: SUB_RATE }, moneyGain: 0 },
  sleep: { id: "sleep", label: "수면", icon: Moon, desc: "체력/면역 대폭 회복", multipliers: { health: BASE_RATE, immunity: BASE_RATE, focus: SUB_RATE }, moneyGain: 0 },
} as const;

export const SHOP_ITEMS = [
  { id: "budget_courier_bike", category: "work", label: "중고 배달 자전거", desc: "자전거 배달 알바 해금 (입문용)", cost: 99, targetAction: "none", boost: 0, icon: Bike },
  { id: "mini_meditation_pod", category: "mind", label: "미니 향초", desc: "명상 효율 +5%", cost: 100, targetAction: "meditation", boost: 1.05, icon: Sparkles },
  { id: "water_tracker_bottle", category: "health", label: "스마트 물병", desc: "휴식 효율 +5%", cost: 120, targetAction: "rest", boost: 1.05, icon: Zap },
  { id: "meal_basic", category: "health", label: "간단한 식사", desc: "체력 +15, 면역 +5 (하루 3회 권장)", cost: 7, consumable: true, restore: { health: 15, immunity: 5 }, icon: Apple },
  { id: "meal_standard", category: "health", label: "든든한 식사", desc: "체력 +25, 면역 +10 (하루 3회 권장)", cost: 12, consumable: true, restore: { health: 25, immunity: 10 }, icon: Apple },
  { id: "meal_premium", category: "health", label: "영양식 세트", desc: "체력 +35, 면역 +15 (가끔)", cost: 18, consumable: true, restore: { health: 35, immunity: 15 }, icon: Apple },
  { id: "notebook_pro", category: "study", label: "프로 노트북 메모장", desc: "공부 효율 +5%", cost: 150, targetAction: "study", boost: 1.05, icon: BookOpen },
  { id: "resistance_band", category: "health", label: "저항 밴드 세트", desc: "운동 효율 +5%", cost: 150, targetAction: "exercise", boost: 1.05, icon: Dumbbell },
  { id: "reading_glasses", category: "study", label: "독서 전용 안경", desc: "독서 효율 +5%", cost: 200, targetAction: "reading", boost: 1.05, icon: Eye },
  { id: "quality_headphones", category: "work", label: "소음 차단 헤드폰", desc: "작업 집중력 +5%", cost: 300, targetAction: "work", boost: 1.05, icon: Headphones },
  { id: "reading_lamp", category: "study", label: "독서용 램프", desc: "독서 효율 +8%", cost: 500, targetAction: "reading", boost: 1.08, icon: Lightbulb },
  { id: "bike", category: "work", label: "중고 오토바이", desc: "오토바이 배달 알바 해금 (고수익)", cost: 800, targetAction: "none", boost: 0, icon: Bike },
  { id: "habit_tracker_app", category: "work", label: "습관 트래커 앱", desc: "작업 효율 +8%", cost: 1500, targetAction: "work", boost: 1.08, icon: Smartphone },
  { id: "focus_notifier", category: "passive", label: "집중 알림 장치", desc: "집중력 자연 감소 10% 방어", cost: 2000, passive: { stat: "focus", rate: 0.9 }, icon: Target },
  { id: "theme_neon", category: "special", label: "네온 테마", desc: "UI 스킨 (미구현)", cost: 2000, cosmetic: true, icon: Star },
  { id: "smart_pen", category: "study", label: "스마트 펜", desc: "공부 효율 +10%", cost: 2500, targetAction: "study", boost: 1.1, icon: PenTool },
  { id: "protein_pack", category: "health", label: "단백질 보충제", desc: "운동 효율 +10%", cost: 2500, targetAction: "exercise", boost: 1.1, icon: Dumbbell },
  { id: "sleep_mask_pillow", category: "health", label: "수면 마스크 & 베개", desc: "수면 회복량 +25%", cost: 3000, targetAction: "sleep", boost: 1.25, icon: Moon },
  { id: "meditation_app", category: "mind", label: "명상 앱 구독", desc: "명상 효율 +15%", cost: 3500, targetAction: "meditation", boost: 1.15, icon: Brain },
  { id: "yoga_mat", category: "special", label: "요가 매트", desc: "휴식 효율 15% 증가", cost: 3500, targetAction: "rest", boost: 1.15, icon: Wind },
  { id: "vitamin_pack", category: "passive", label: "비타민 패키지", desc: "면역력 자연 감소 20% 방어", cost: 4000, passive: { stat: "immunity", rate: 0.8 }, icon: Pill },
  { id: "kindle", category: "study", label: "전자책 리더기", desc: "독서 효율 +20%", cost: 4000, targetAction: "reading", boost: 1.2, icon: BookOpen },
  { id: "gym_pass", category: "health", label: "헬스장 회원권", desc: "운동 효율 +20%", cost: 5000, targetAction: "exercise", boost: 1.2, icon: Activity },
  { id: "pet_slime", category: "special", label: "슬라임 펫", desc: "귀여움 (심리적 안정)", cost: 5000, cosmetic: true, icon: Ghost },
  { id: "office_chair", category: "work", label: "인체공학 의자", desc: "업무 효율 +15%", cost: 5500, targetAction: "work", boost: 1.15, icon: Armchair },
  { id: "aroma_candle", category: "mind", label: "고급 아로마 세트", desc: "명상 효율 +25%", cost: 6000, targetAction: "meditation", boost: 1.25, icon: Sparkles },
  { id: "air_purifier", category: "passive", label: "공기청정기", desc: "집중력 자연 감소 20% 방어", cost: 7000, passive: { stat: "focus", rate: 0.8 }, icon: Wind },
  { id: "nutrition_pack", category: "special", label: "영양 키트", desc: "음주/게임 패널티 30% 감소", cost: 7000, passive: { type: "penalty", rate: 0.7 }, icon: Apple },
  { id: "productivity_app", category: "work", label: "업무 자동화 툴", desc: "업무 효율 +20%", cost: 8000, targetAction: "work", boost: 1.2, icon: AppWindow },
  { id: "sleep_tracker", category: "special", label: "수면 분석기", desc: "수면 효율 30% 증가", cost: 8000, passive: { type: "sleep", rate: 1.3 }, icon: MoonStar },
  { id: "standing_desk", category: "special", label: "스탠딩 데스크", desc: "업무 중 체력 감소 완화 (미구현)", cost: 9000, targetAction: "work", boost: 1.1, icon: MoveVertical },
  { id: "therapy_sessions", category: "passive", label: "테라피 세션", desc: "정서 자연 감소 30% 방어", cost: 10000, passive: { stat: "eq", rate: 0.7 }, icon: Smile },
  { id: "premium_textbook", category: "study", label: "프리미엄 교재", desc: "공부 효율 +40%", cost: 12000, targetAction: "study", boost: 1.4, icon: GraduationCap },
  { id: "coding_monitor", category: "work", label: "트리플 모니터", desc: "업무 효율 +30%", cost: 15000, targetAction: "work", boost: 1.3, icon: Monitor },
  { id: "habit_streaker", category: "passive", label: "습관 관리기", desc: "모든 스탯 감소 10% 방어", cost: 15000, passive: { stat: "all", rate: 0.9 }, icon: Link },
  { id: "mini_drone", category: "special", label: "감시 드론", desc: "공백기(Gap) 보상 20% 증가", cost: 15000, passive: { type: "gap", rate: 1.2 }, icon: Plane },
  { id: "silent_room", category: "mind", label: "방음 부스", desc: "명상 효율 +40%", cost: 20000, targetAction: "meditation", boost: 1.4, icon: Lock },
  { id: "home_gym", category: "health", label: "홈짐 세트", desc: "운동 효율 +50%", cost: 25000, targetAction: "exercise", boost: 1.5, icon: Zap },
  { id: "premium_ai_mentor", category: "special", label: "AI 멘토", desc: "모든 성장 효율 5% 증가", cost: 30000, passive: { type: "growth", rate: 1.05 }, icon: Bot },
  { id: "pro_tool", category: "work", label: "전문가용 장비", desc: "업무 효율 +50% (End Game)", cost: 50000, targetAction: "work", boost: 1.5, icon: Zap },
] as const;

export const GAP_ACTIVITIES = {
  sleep: { id: "sleep", label: "수면 (숙면)", icon: Moon, effect: { health: 0.2, immunity: 0.2 }, money: 0, desc: "체력이 회복되었습니다." },
  work: { id: "work", label: "생업/업무", icon: Zap, effect: { health: -0.05, focus: -0.05 }, money: "dynamic" as const, desc: "일을 했습니다. 자산 증가, 피로 누적." },
  transit: { id: "transit", label: "이동/가사", icon: User, effect: { health: -0.01 }, money: 0, desc: "필수적인 생활 시간이었습니다." },
  idle: { id: "idle", label: "SNS/무의미한 시간", icon: Smartphone, effect: { focus: -0.2, willpower: -0.1 }, money: -0.5, desc: "도파민 중독. 집중력과 시간이 낭비되었습니다." },
  gaming: { id: "gaming", label: "게임/오락", icon: Gamepad2, effect: { health: -0.1, focus: -0.2 }, money: -1, desc: "현실 성장을 멈추고 가상에 투자했습니다." },
  drinking: { id: "drinking", label: "음주/유흥", icon: Beer, effect: { health: -0.5, immunity: -0.5, intelligence: -0.3 }, money: -5, desc: "신체 능력과 자산이 심각하게 손상됩니다." },
} as const;

export const QUESTS: QuestDefinition[] = [
  {
    id: "daily_study_10",
    type: "daily",
    tier: 1,
    difficulty: 3,
    label: "첫 걸음 - 10분 학습",
    description: "모든 위대한 여정은 작은 한 걸음에서 시작됩니다.",
    target: { kind: "single", category: "study", minutes: 10 },
    targetMinutes: 10,
    reward: { money: 10, intelligence: 2, willpower: 1 },
    unlockCondition: null,
    flavorText: "10분의 집중은 10시간의 방황보다 가치있습니다.",
  },
  {
    id: "daily_study_20",
    type: "daily",
    tier: 2,
    difficulty: 3,
    label: "기본 학습 - 20분",
    description: "규칙적인 학습은 천재성을 이깁니다.",
    target: { kind: "single", category: "study", minutes: 20 },
    targetMinutes: 20,
    reward: { money: 20, intelligence: 3, willpower: 2 },
    unlockCondition: { type: "questComplete", questId: "daily_study_10", count: 3 },
    flavorText: "꾸준함이 재능을 만듭니다.",
  },
  {
    id: "daily_study_30",
    type: "daily",
    tier: 3,
    difficulty: 3,
    label: "집중 학습 - 30분",
    description: "30분의 몰입은 뇌의 구조를 재배열합니다.",
    target: { kind: "single", category: "study", minutes: 30 },
    targetMinutes: 30,
    reward: { money: 30, intelligence: 5, willpower: 3 },
    unlockCondition: { type: "questComplete", questId: "daily_study_20", count: 5 },
    flavorText: "진정한 학습은 불편함에서 시작됩니다.",
  },
  {
    id: "daily_study_60",
    type: "daily",
    tier: 4,
    difficulty: 4,
    label: "심화 학습 - 60분",
    description: "한 시간의 몰입은 하루의 산만함을 압도합니다.",
    target: { kind: "single", category: "study", minutes: 60 },
    targetMinutes: 60,
    reward: { money: 79, intelligence: 8, willpower: 6 },
    unlockCondition: { type: "questComplete", questId: "daily_study_30", count: 7 },
    flavorText: "이 경지에 오른 자는 많지 않습니다.",
  },
  {
    id: "daily_study_90",
    type: "daily",
    tier: 5,
    difficulty: 5,
    label: "마스터 학습 - 90분",
    description: "90분간 세상과 단절하고 지식과 하나됩니다.",
    target: { kind: "single", category: "study", minutes: 90 },
    targetMinutes: 90,
    reward: { money: 149, intelligence: 12, willpower: 10 },
    unlockCondition: { type: "questComplete", questId: "daily_study_60", count: 10 },
    flavorText: "마스터의 영역에 들어섰습니다.",
  },
  {
    id: "daily_exercise_10",
    type: "daily",
    tier: 1,
    difficulty: 3,
    label: "몸의 각성 - 10분 운동",
    description: "10분이면 충분합니다. 몸을 깨우세요.",
    target: { kind: "single", category: "exercise", minutes: 10 },
    targetMinutes: 10,
    reward: { money: 10, health: 3, immunity: 2 },
    unlockCondition: null,
    flavorText: "정지된 몸은 정지된 마음을 낳습니다.",
  },
  {
    id: "daily_exercise_20",
    type: "daily",
    tier: 2,
    difficulty: 3,
    label: "활력 충전 - 20분 운동",
    description: "20분의 움직임으로 하루를 완전히 바꾸세요.",
    target: { kind: "single", category: "exercise", minutes: 20 },
    targetMinutes: 20,
    reward: { money: 20, health: 5, immunity: 4 },
    unlockCondition: { type: "questComplete", questId: "daily_exercise_10", count: 3 },
    flavorText: "땀 한 방울은 게으름 백 개를 씻어냅니다.",
  },
  {
    id: "daily_exercise_30",
    type: "daily",
    tier: 3,
    difficulty: 4,
    label: "강화 운동 - 30분",
    description: "30분간 몸의 한계와 대화하세요.",
    target: { kind: "single", category: "exercise", minutes: 30 },
    targetMinutes: 30,
    reward: { money: 40, health: 8, immunity: 6 },
    unlockCondition: { type: "questComplete", questId: "daily_exercise_20", count: 5 },
    flavorText: "고통은 일시적입니다. 성장은 영원합니다.",
  },
  {
    id: "daily_exercise_45",
    type: "daily",
    tier: 4,
    difficulty: 5,
    label: "한계 돌파 - 45분 운동",
    description: "45분의 운동은 당신을 다른 차원으로 이끕니다.",
    target: { kind: "single", category: "exercise", minutes: 45 },
    targetMinutes: 45,
    reward: { money: 74, health: 11, immunity: 9 },
    unlockCondition: { type: "questComplete", questId: "daily_exercise_30", count: 7 },
    flavorText: "강한 몸에는 강한 정신이 깃듭니다.",
  },
  {
    id: "daily_exercise_60",
    type: "daily",
    tier: 5,
    difficulty: 5,
    label: "전사의 수련 - 60분 운동",
    description: "60분의 수련으로 완전한 변화를 경험하세요.",
    target: { kind: "single", category: "exercise", minutes: 60 },
    targetMinutes: 60,
    reward: { money: 99, health: 15, immunity: 12 },
    unlockCondition: { type: "questComplete", questId: "daily_exercise_45", count: 10 },
    flavorText: "진정한 전사의 경지입니다.",
  },
  {
    id: "daily_meditation_5",
    type: "daily",
    tier: 1,
    difficulty: 3,
    label: "찰나의 고요 - 5분 명상",
    description: "5분의 침묵으로 세상의 소음을 잠재웁니다.",
    target: { kind: "single", category: "meditation", minutes: 5 },
    targetMinutes: 5,
    reward: { money: 5, eq: 2, willpower: 1 },
    unlockCondition: null,
    flavorText: "고요함은 선택입니다.",
  },
  {
    id: "daily_meditation_10",
    type: "daily",
    tier: 2,
    difficulty: 4,
    label: "마음의 정원 - 10분 명상",
    description: "10분간 당신의 내면을 관찰하세요.",
    target: { kind: "single", category: "meditation", minutes: 10 },
    targetMinutes: 10,
    reward: { money: 13, eq: 4, willpower: 2 },
    unlockCondition: { type: "questComplete", questId: "daily_meditation_5", count: 3 },
    flavorText: "관찰자가 되는 순간, 당신은 자유로워집니다.",
  },
  {
    id: "daily_meditation_20",
    type: "daily",
    tier: 3,
    difficulty: 5,
    label: "심층 명상 - 20분",
    description: "20분간 생각의 흐름을 관찰하세요.",
    target: { kind: "single", category: "meditation", minutes: 20 },
    targetMinutes: 20,
    reward: { money: 33, eq: 7, willpower: 5 },
    unlockCondition: { type: "questComplete", questId: "daily_meditation_10", count: 5 },
    flavorText: "생각이 당신이 아닙니다. 당신은 생각을 보는 자입니다.",
  },
  {
    id: "daily_meditation_30",
    type: "daily",
    tier: 4,
    difficulty: 5,
    label: "깊은 평온 - 30분 명상",
    description: "30분의 명상으로 마음의 평화를 찾으세요.",
    target: { kind: "single", category: "meditation", minutes: 30 },
    targetMinutes: 30,
    reward: { money: 50, eq: 10, willpower: 8 },
    unlockCondition: { type: "questComplete", questId: "daily_meditation_20", count: 7 },
    flavorText: "비움이 곧 채움입니다.",
  },
  {
    id: "daily_work_30",
    type: "daily",
    tier: 1,
    difficulty: 3,
    label: "업무 시작 - 30분",
    description: "30분의 집중으로 하루를 열어갑니다.",
    target: { kind: "single", category: "work", minutes: 30 },
    targetMinutes: 30,
    reward: { money: 30, focus: 2, willpower: 1 },
    unlockCondition: null,
    flavorText: "시작이 반입니다.",
  },
  {
    id: "daily_work_60",
    type: "daily",
    tier: 2,
    difficulty: 4,
    label: "집중 업무 - 60분",
    description: "60분의 집중으로 전문성을 쌓습니다.",
    target: { kind: "single", category: "work", minutes: 60 },
    targetMinutes: 60,
    reward: { money: 79, focus: 4, willpower: 3 },
    unlockCondition: { type: "questComplete", questId: "daily_work_30", count: 3 },
    flavorText: "반복이 숙련을 낳습니다.",
  },
  {
    id: "daily_work_90",
    type: "daily",
    tier: 3,
    difficulty: 4,
    label: "몰입 업무 - 90분",
    description: "90분간 완전히 일에 빠져듭니다.",
    target: { kind: "single", category: "work", minutes: 90 },
    targetMinutes: 90,
    reward: { money: 119, focus: 6, willpower: 5 },
    unlockCondition: { type: "questComplete", questId: "daily_work_60", count: 5 },
    flavorText: "몰입하는 자는 시간의 주인이 됩니다.",
  },
  {
    id: "daily_work_120",
    type: "daily",
    tier: 4,
    difficulty: 4,
    label: "심화 업무 - 120분",
    description: "2시간의 집중 근로로 불가능을 가능으로.",
    target: { kind: "single", category: "work", minutes: 120 },
    targetMinutes: 120,
    reward: { money: 158, focus: 9, willpower: 7 },
    unlockCondition: { type: "questComplete", questId: "daily_work_90", count: 7 },
    flavorText: "이 경지에 이른 자는 스스로를 초월합니다.",
  },
  {
    id: "daily_sleep_30",
    type: "daily",
    tier: 1,
    difficulty: 3,
    label: "파워 냅 - 30분",
    description: "30분의 수면으로 재충전하세요.",
    target: { kind: "single", category: "sleep", minutes: 30 },
    targetMinutes: 30,
    reward: { money: 10, health: 4, immunity: 3 },
    unlockCondition: null,
    flavorText: "짧지만 강렬한 휴식입니다.",
  },
  {
    id: "daily_sleep_90",
    type: "daily",
    tier: 2,
    difficulty: 3,
    label: "완전한 휴식 - 90분",
    description: "90분의 완전한 수면 사이클로 몸을 재생합니다.",
    target: { kind: "single", category: "sleep", minutes: 90 },
    targetMinutes: 90,
    reward: { money: 30, health: 8, immunity: 7 },
    unlockCondition: { type: "questComplete", questId: "daily_sleep_30", count: 3 },
    flavorText: "수면은 최고의 약입니다.",
  },
  {
    id: "weekly_study_300",
    type: "weekly",
    tier: 1,
    difficulty: 5,
    label: "주간 학습 목표 - 5시간",
    description: "이번 주 300분(5시간)의 학습으로 지성을 확장하세요.",
    target: { kind: "single", category: "study", minutes: 300 },
    targetMinutes: 300,
    reward: { money: 495, intelligence: 15, willpower: 10 },
    unlockCondition: null,
    flavorText: "일주일의 헌신이 평생의 자산이 됩니다.",
  },
  {
    id: "weekly_study_480",
    type: "weekly",
    tier: 2,
    difficulty: 5,
    label: "집중 학습 주간 - 8시간",
    description: "이번 주 480분(8시간), 진정한 학습자의 길입니다.",
    target: { kind: "single", category: "study", minutes: 480 },
    targetMinutes: 480,
    reward: { money: 792, intelligence: 22, willpower: 15 },
    unlockCondition: { type: "statRequirement", stat: "intelligence", value: 30 },
    flavorText: "이 정도면 전문가 수준입니다.",
  },
  {
    id: "weekly_exercise_240",
    type: "weekly",
    tier: 1,
    difficulty: 6,
    label: "주간 운동 목표 - 4시간",
    description: "이번 주 240분(4시간)의 운동으로 몸을 강화하세요.",
    target: { kind: "single", category: "exercise", minutes: 240 },
    targetMinutes: 240,
    reward: { money: 475, health: 18, immunity: 15 },
    unlockCondition: null,
    flavorText: "변화는 한순간에 오지 않지만, 반드시 옵니다.",
  },
  {
    id: "weekly_exercise_360",
    type: "weekly",
    tier: 2,
    difficulty: 6,
    label: "강화 운동 주간 - 6시간",
    description: "이번 주 360분(6시간) 운동, 상위 1%의 길입니다.",
    target: { kind: "single", category: "exercise", minutes: 360 },
    targetMinutes: 360,
    reward: { money: 713, health: 25, immunity: 20 },
    unlockCondition: { type: "statRequirement", stat: "health", value: 40 },
    flavorText: "이 몸으로 무엇이든 할 수 있습니다.",
  },
  {
    id: "weekly_meditation_180",
    type: "weekly",
    tier: 1,
    difficulty: 6,
    label: "주간 명상 목표 - 3시간",
    description: "이번 주 180분(3시간)의 명상으로 마음을 정돈하세요.",
    target: { kind: "single", category: "meditation", minutes: 180 },
    targetMinutes: 180,
    reward: { money: 356, eq: 18, willpower: 15 },
    unlockCondition: null,
    flavorText: "고요함이 당신의 무기입니다.",
  },
  {
    id: "weekly_work_360",
    type: "weekly",
    tier: 1,
    difficulty: 6,
    label: "주간 업무 목표 - 6시간",
    description: "이번 주 360분(6시간)의 집중 근로로 전문가가 되세요.",
    target: { kind: "single", category: "work", minutes: 360 },
    targetMinutes: 360,
    reward: { money: 713, focus: 18, willpower: 12 },
    unlockCondition: null,
    flavorText: "이 정도 일하면 성공은 필연입니다.",
  },
  {
    id: "weekly_balanced",
    type: "weekly",
    tier: 1,
    difficulty: 5,
    label: "균형의 주간",
    description: "이번 주 공부, 운동, 명상 각 60분 이상 달성하세요.",
    target: { kind: "multi", requirements: { study: 60, exercise: 60, meditation: 60 } },
    targetMinutes: 180,
    reward: { money: 297, intelligence: 8, health: 8, eq: 8, willpower: 10 },
    unlockCondition: { type: "level", value: 5 },
    flavorText: "진정한 강자는 균형을 잃지 않습니다.",
  },
  {
    id: "weekly_consistency",
    type: "weekly",
    tier: 2,
    difficulty: 10,
    label: "꾸준함의 힘",
    description: "이번 주 매일 최소 20분 이상 학습하세요.",
    target: { kind: "single", category: "study", minutes: 20 },
    targetMinutes: 140,
    conditions: [{ type: "dailyMinimum", daysRequired: 7, minimumMinutes: 20 }],
    reward: { money: 462, intelligence: 18, willpower: 15 },
    unlockCondition: { type: "statRequirement", stat: "willpower", value: 30 },
    flavorText: "매일 하는 것이 많이 하는 것보다 중요합니다.",
  },
  {
    id: "milestone_study_500",
    type: "milestone",
    tier: 1,
    difficulty: 5,
    label: "학습자의 입문 - 500분",
    description: "누적 500분 학습, 학습자의 길에 들어섰습니다.",
    target: { kind: "single", category: "study", minutes: 500 },
    targetMinutes: 500,
    reward: { money: 825, intelligence: 20, willpower: 12 },
    unlockCondition: null,
    flavorText: "입문은 끝이 아니라 시작입니다.",
  },
  {
    id: "milestone_study_1000",
    type: "milestone",
    tier: 2,
    difficulty: 5,
    label: "지식의 탐구자 - 1000분",
    description: "누적 1000분 학습 달성. 당신의 뇌는 이미 다릅니다.",
    target: { kind: "single", category: "study", minutes: 1000 },
    targetMinutes: 1000,
    reward: { money: 1650, intelligence: 30, willpower: 20 },
    unlockCondition: null,
    flavorText: "천 분의 여정, 만 분의 시작.",
  },
  {
    id: "milestone_study_3000",
    type: "milestone",
    tier: 3,
    difficulty: 5,
    label: "학자의 경지 - 3000분",
    description: "누적 3000분, 당신은 이미 전문가 수준입니다.",
    target: { kind: "single", category: "study", minutes: 3000 },
    targetMinutes: 3000,
    reward: { money: 4950, intelligence: 50, willpower: 30 },
    unlockCondition: { type: "statRequirement", stat: "intelligence", value: 50 },
    flavorText: "지식은 이제 당신의 일부입니다.",
    rarity: "epic",
  },
  {
    id: "milestone_study_10000",
    type: "milestone",
    tier: 4,
    difficulty: 5,
    label: "만 분의 법칙 - 마스터",
    description: "누적 10000분 학습. 당신은 진정한 마스터입니다.",
    target: { kind: "single", category: "study", minutes: 10000 },
    targetMinutes: 10000,
    reward: { money: 16500, intelligence: 100, willpower: 50 },
    unlockCondition: { type: "statRequirement", stat: "intelligence", value: 100 },
    flavorText: "말콤 글래드웰이 옳았습니다. 당신이 증명입니다.",
    rarity: "legendary",
  },
  {
    id: "milestone_exercise_500",
    type: "milestone",
    tier: 1,
    difficulty: 5,
    label: "운동의 시작 - 500분",
    description: "누적 500분 운동, 몸이 깨어나기 시작했습니다.",
    target: { kind: "single", category: "exercise", minutes: 500 },
    targetMinutes: 500,
    reward: { money: 825, health: 20, immunity: 15 },
    unlockCondition: null,
    flavorText: "강한 몸은 강한 인생의 기초입니다.",
  },
  {
    id: "milestone_exercise_1000",
    type: "milestone",
    tier: 2,
    difficulty: 5,
    label: "철인의 길 - 1000분",
    description: "누적 1000분 운동, 당신은 철인입니다.",
    target: { kind: "single", category: "exercise", minutes: 1000 },
    targetMinutes: 1000,
    reward: { money: 1650, health: 30, immunity: 25 },
    unlockCondition: null,
    flavorText: "이 몸으로 세상을 정복할 수 있습니다.",
  },
  {
    id: "milestone_exercise_3000",
    type: "milestone",
    tier: 3,
    difficulty: 5,
    label: "강철 전사 - 3000분",
    description: "누적 3000분 운동, 당신의 몸은 강철입니다.",
    target: { kind: "single", category: "exercise", minutes: 3000 },
    targetMinutes: 3000,
    reward: { money: 4950, health: 50, immunity: 40 },
    unlockCondition: { type: "statRequirement", stat: "health", value: 70 },
    flavorText: "평범한 사람들은 이 경지를 상상조차 못합니다.",
    rarity: "epic",
  },
  {
    id: "milestone_meditation_500",
    type: "milestone",
    tier: 1,
    difficulty: 5,
    label: "마음의 탐험 - 500분",
    description: "누적 500분 명상, 내면의 여행이 시작됐습니다.",
    target: { kind: "single", category: "meditation", minutes: 500 },
    targetMinutes: 500,
    reward: { money: 825, eq: 20, willpower: 15 },
    unlockCondition: null,
    flavorText: "침묵 속에서 당신은 자신을 발견합니다.",
  },
  {
    id: "milestone_meditation_1000",
    type: "milestone",
    tier: 2,
    difficulty: 5,
    label: "자아 인식 - 1000분",
    description: "누적 1000분 명상, 당신은 자신을 이해하기 시작했습니다.",
    target: { kind: "single", category: "meditation", minutes: 1000 },
    targetMinutes: 1000,
    reward: { money: 1650, eq: 30, willpower: 22 },
    unlockCondition: null,
    flavorText: "자아 인식은 모든 성장의 출발점입니다.",
  },
  {
    id: "milestone_work_1000",
    type: "milestone",
    tier: 1,
    difficulty: 6,
    label: "전문가의 길 - 1000분",
    description: "누적 1000분 근로, 전문가의 길에 들어섰습니다.",
    target: { kind: "single", category: "work", minutes: 1000 },
    targetMinutes: 1000,
    reward: { money: 1980, focus: 20, willpower: 15 },
    unlockCondition: null,
    flavorText: "일에 대한 헌신이 미래를 만듭니다.",
  },
  {
    id: "milestone_work_3000",
    type: "milestone",
    tier: 2,
    difficulty: 6,
    label: "장인의 경지 - 3000분",
    description: "누적 3000분 근로, 당신은 진정한 장인입니다.",
    target: { kind: "single", category: "work", minutes: 3000 },
    targetMinutes: 3000,
    reward: { money: 5940, focus: 35, willpower: 25 },
    unlockCondition: { type: "statRequirement", stat: "focus", value: 40 },
    flavorText: "장인의 경지는 시간으로 증명됩니다.",
    rarity: "epic",
  },
  {
    id: "milestone_polymath",
    type: "milestone",
    tier: 3,
    difficulty: 10,
    label: "르네상스인 - 만능의 달인",
    description: "모든 카테고리에서 누적 1000분 이상 달성하세요.",
    target: {
      kind: "multi",
      requirements: { study: 1000, exercise: 1000, meditation: 1000, work: 1000 },
    },
    targetMinutes: 4000,
    reward: { money: 13200, intelligence: 40, health: 40, eq: 40, focus: 40, willpower: 50 },
    unlockCondition: { type: "level", value: 20 },
    flavorText: "레오나르도 다 빈치도 당신을 인정할 것입니다.",
    rarity: "legendary",
  },
  {
    id: "milestone_sleep_master",
    type: "milestone",
    tier: 1,
    difficulty: 4,
    label: "수면의 마스터 - 2000분",
    description: "누적 2000분 수면 기록, 회복의 중요성을 압니다.",
    target: { kind: "single", category: "sleep", minutes: 2000 },
    targetMinutes: 2000,
    reward: { money: 2640, health: 30, immunity: 25 },
    unlockCondition: null,
    flavorText: "휴식은 나약함이 아니라 전략입니다.",
  },
  {
    id: "chain_study_3",
    type: "chain",
    tier: 1,
    difficulty: 5,
    label: "학습 습관 - 3일 연속",
    description: "3일 연속 공부 20분 이상을 달성하세요.",
    target: { kind: "single", category: "study", minutes: 20 },
    targetMinutes: 60,
    conditions: [{ type: "streak", consecutiveDays: 3 }],
    reward: { money: 99, intelligence: 8, willpower: 6 },
    unlockCondition: null,
    flavorText: "습관은 3일부터 시작됩니다.",
  },
  {
    id: "chain_study_7",
    type: "chain",
    tier: 2,
    difficulty: 7,
    label: "학습의 주간 - 7일 연속",
    description: "7일 연속 공부 20분 이상을 달성하세요.",
    target: { kind: "single", category: "study", minutes: 20 },
    targetMinutes: 140,
    conditions: [{ type: "streak", consecutiveDays: 7 }],
    reward: { money: 323, intelligence: 15, willpower: 12 },
    unlockCondition: { type: "questComplete", questId: "chain_study_3", count: 1 },
    flavorText: "일주일의 연속은 습관을 만듭니다.",
  },
  {
    id: "chain_exercise_3",
    type: "chain",
    tier: 1,
    difficulty: 5,
    label: "운동 습관 - 3일 연속",
    description: "3일 연속 운동 15분 이상을 달성하세요.",
    target: { kind: "single", category: "exercise", minutes: 15 },
    targetMinutes: 45,
    conditions: [{ type: "streak", consecutiveDays: 3 }],
    reward: { money: 74, health: 10, immunity: 8 },
    unlockCondition: null,
    flavorText: "몸은 움직임을 기억합니다.",
  },
  {
    id: "chain_meditation_7",
    type: "chain",
    tier: 1,
    difficulty: 7,
    label: "명상의 일주일 - 7일 연속",
    description: "7일 연속 명상 10분 이상을 달성하세요.",
    target: { kind: "single", category: "meditation", minutes: 10 },
    targetMinutes: 70,
    conditions: [{ type: "streak", consecutiveDays: 7 }],
    reward: { money: 162, eq: 15, willpower: 12 },
    unlockCondition: null,
    flavorText: "고요함은 하루아침에 오지 않습니다.",
  },
] as const;

export const LONG_TERM_GOALS = [
  { id: "wealth", label: "억만장자 (자산/지능)", boost: ["intelligence"] as StatKey[], rec: ["work", "study"] as ActionId[] },
  { id: "health", label: "신체 개조 (체력/면역)", boost: ["health", "immunity"] as StatKey[], rec: ["exercise", "sleep"] as ActionId[] },
  { id: "mind", label: "멘탈 마스터 (정서/의지)", boost: ["eq", "willpower"] as StatKey[], rec: ["meditation", "reading"] as ActionId[] },
] as const;
