export const BALANCE = {
  NUMBER: {
    ZERO: 0,
    ONE: 1,
    TWO: 2,
    THREE: 3,
    FOUR: 4,
    FIVE: 5,
    SIX: 6,
    TEN: 10,
    TWENTY_FIVE: 25,
    FIFTY: 50,
    SIXTY: 60,
    SEVENTY: 70,
    EIGHTY: 80,
    NINETY: 90,
    ONE_HUNDRED: 100,
  },
  TIME: {
    DAY_START: 420,
    DAY_END: 1380,
    DAY_LENGTH: 1440,
    ACTIVE_MINUTES: 960,
    TICK_MINUTES: 1,
    ACTION_MEMORY_MINUTES: 1,
    CALM_REWARD_WINDOW_MINUTES: 1,
    CLEANUP_MINUTES: 2,
  },
  RNG: {
    INCREMENT: 0x6d2b79f5,
    MIX_SHIFT_A: 15,
    MIX_MULTIPLIER_A: 1,
    MIX_SHIFT_B: 7,
    MIX_MULTIPLIER_B: 61,
    MIX_SHIFT_C: 14,
    UINT32_RANGE: 4294967296,
    FALLBACK_SEED: 1,
  },
  INITIAL: {
    STATS: {
      hunger: 55,
      thirst: 35,
      bowelPressure: 10,
      fatigue: 20,
      stress: 18,
      excitement: 28,
      boredom: 32,
      comfort: 60,
    },
    MEMORY: {
      approachSafety: 55,
      recallTrust: 35,
      nameSkill: 30,
      waitSkill: 20,
      matExpectation: 15,
      coproHabit: 30,
      snatchExpectation: 20,
      hiddenPoopTendency: 18,
      attentionViaPoop: 14,
    },
    MAT_SKILL: 40,
    MAT_SKILL_OWNER_AWAY: 10,
    PERSONALITY_MIN: 35,
    PERSONALITY_MAX: 75,
  },
  PHYSIOLOGY: {
    HUNGER_PER_MINUTE: 0.1,
    THIRST_PER_MINUTE: 0.14,
    FATIGUE_PER_MINUTE: 0.04,
    BOREDOM_PER_MINUTE: 0.05,
    STRESS_RECOVERY_PER_MINUTE: 0.025,
    EXCITEMENT_RECOVERY_PER_MINUTE: 0.06,
    COMFORT_DECAY_PER_MINUTE: 0.015,
    FEED_HUNGER_REDUCTION_PER_VOLUME: 0.3,
    FEED_COMFORT_GAIN_PER_VOLUME: 0.04,
    WATER_DEFAULT_VOLUME: 25,
    WATER_THIRST_REDUCTION_PER_VOLUME: 0.7,
    WALK_HUNGER_PER_MINUTE: 0.08,
    WALK_THIRST_PER_MINUTE: 0.12,
    WALK_FATIGUE_PER_MINUTE: 0.25,
    WALK_STRESS_REDUCTION_PER_MINUTE: 0.22,
    WALK_BOREDOM_REDUCTION_PER_MINUTE: 0.28,
    PLAY_HUNGER_PER_MINUTE: 0.04,
    PLAY_THIRST_PER_MINUTE: 0.08,
    PLAY_FATIGUE_PER_MINUTE: 0.18,
    PLAY_STRESS_REDUCTION_PER_MINUTE: 0.12,
    PLAY_EXCITEMENT_PER_MINUTE: 0.35,
    PLAY_BOREDOM_REDUCTION_PER_MINUTE: 0.42,
  },
  DIGESTION: {
    BASE_MINUTES: 240,
    VARIANCE_MINUTES: 60,
    STRESS_DELAY_MAX_MINUTES: 30,
    WALK_CORRECTION_PER_MINUTE: 0.35,
    PLAY_CORRECTION_PER_MINUTE: 0.15,
    PRESSURE_PER_VOLUME: 0.95,
    PRESSURE_SIGNAL: 70,
    PRESSURE_POOP: 88,
    PRESSURE_AFTER_POOP: 12,
    POOP_DELAY_MINUTES_MIN: 18,
    POOP_DELAY_MINUTES_MAX: 25,
    SIGNAL_LEAD_MINUTES: [15, 12, 10],
    EAT_DELAY_MINUTES: 2,
    EAT_DELAY_SNATCH_MINUTES: 1,
    FAST_SNATCH_THRESHOLD: 60,
    EAT_COPRO_GAIN: 4,
    EAT_SNATCH_GAIN: 1,
    EAT_HUNGER_REDUCTION: 4,
    PAD_BASE_CHANCE: 0.05,
    PAD_SKILL_FACTOR: 0.002,
    HIDDEN_CHANCE_FACTOR: 0.01,
  },
  DECISION: {
    NOISE: 6,
    BLOCK_PENALTY: -1000,
    HIDDEN_OWNER_PENALTY: -40,
    SNIFF_BASE: 45,
    EAT: {
      FOOD_DRIVE: 0.35,
      HUNGER: 0.3,
      COPRO_HABIT: 0.5,
      SNATCH_EXPECTATION: 0.4,
      MAT_EXPECTATION: -0.4,
      WAIT_SKILL: -0.3,
    },
    MAT: {
      MAT_SKILL: 0.6,
      MAT_EXPECTATION: 0.4,
      APPROACH_SAFETY: 0.25,
      EXCITEMENT: -0.3,
      STRESS: -0.25,
    },
    WATCH: {
      ATTENTION_VIA_POOP: 0.5,
      SOCIABILITY: 0.3,
    },
    FLEE: {
      APPROACH_DANGER: 0.6,
      STRESS: 0.3,
    },
    SNIFF: {
      COMFORT: 0.3,
      COPRO_HABIT: -0.4,
    },
    ZOOMIES: {
      EXCITEMENT: 0.4,
      BOREDOM: 0.3,
      FATIGUE: -0.3,
    },
  },
  LEARNING: {
    MAT_EXPECTATION_REWARD: 6,
    MAT_SKILL_REWARD: 5,
    MAT_COPRO_REDUCTION: 3,
    GENERALIZE_RATE: 0.25,
    OWNER_AWAY_GENERALIZE_RATE: 0.1,
    POOP_ATTENTION_REWARD: 7,
    POOP_COPRO_REWARD: 2,
    CALM_APPROACH_GAIN: 2,
    CALM_RECALL_GAIN: 4,
    MAT_FAILURE_LOSS: 1,
    SCOLD_APPROACH_LOSS: 7,
    SCOLD_SNATCH_GAIN: 8,
    SCOLD_HIDDEN_GAIN: 5,
  },
  INTERVENTION: {
    CALM_BASE_CHANCE: 0.2,
    CALM_RECALL_FACTOR: 0.007,
    CALM_EXCITEMENT_FACTOR: 0.004,
    MAT_BASE_CHANCE: 0.3,
    MAT_SKILL_FACTOR: 0.009,
    MAT_STRESS_FACTOR: 0.003,
    SCOLD_STOP_CHANCE: 0.8,
    SCOLD_EXCITEMENT_GAIN: 15,
    SCOLD_STRESS_GAIN: 10,
    TOY_BASE_CHANCE: 0.3,
    TOY_BOREDOM_FACTOR: 0.006,
    TOY_FOOD_DRIVE_FACTOR: 0.003,
  },
  SPATIAL: {
    MIN_COORDINATE: 0,
    MAX_COORDINATE: 1,
    RANDOM_TARGET_MIN: 0.14,
    RANDOM_TARGET_MAX: 0.86,
    SPEED_PER_MINUTE: 0.18,
    AMBIENT_MIN_INTERVAL_MINUTES: 12,
    AMBIENT_MAX_INTERVAL_MINUTES: 24,
    NEED_THRESHOLD: {
      HUNGER: 68,
      THIRST: 68,
      FATIGUE: 70,
      BOREDOM: 62,
    },
    INITIAL: {
      living: { x: 0.48, y: 0.56 },
      kitchen: { x: 0.5, y: 0.55 },
      toilet: { x: 0.5, y: 0.55 },
    },
    TARGET: {
      MAT: {
        living: { x: 0.24, y: 0.72 },
        kitchen: { x: 0.22, y: 0.72 },
        toilet: { x: 0.22, y: 0.72 },
      },
      FOOD: { room: "kitchen", x: 0.3, y: 0.25 },
      WATER: { room: "kitchen", x: 0.72, y: 0.28 },
      REST: { room: "living", x: 0.22, y: 0.78 },
      PLAY: { room: "living", x: 0.7, y: 0.7 },
      POOP_PAD: { room: "toilet", x: 0.72, y: 0.7 },
      CORNER: {
        living: { x: 0.82, y: 0.82 },
        kitchen: { x: 0.82, y: 0.82 },
        toilet: { x: 0.82, y: 0.82 },
      },
    },
    TRANSITION: {
      living: {
        kitchen: {
          exit: { x: 0.97, y: 0.25 },
          entry: { x: 0.03, y: 0.72 },
        },
        toilet: {
          exit: { x: 0.97, y: 0.75 },
          entry: { x: 0.03, y: 0.28 },
        },
      },
      kitchen: {
        living: {
          exit: { x: 0.03, y: 0.72 },
          entry: { x: 0.97, y: 0.25 },
        },
      },
      toilet: {
        living: {
          exit: { x: 0.03, y: 0.28 },
          entry: { x: 0.97, y: 0.75 },
        },
      },
    },
  },
  LIFESTYLE: {
    ENCOUNTER: {
      FIRST_START_SECONDS: 5,
      HINT_IDLE_SECONDS: 8,
      HINT_INTERVAL_ENCOUNTERS: 3,
      BASE_SCORE: 100,
      BASE_CARE_POINTS: 1,
    },
    OWNER: {
      SPEED_PER_MINUTE: 0.22,
      DIRECT_STEP_DISTANCE: 0.02,
      DOOR_RADIUS: 0.08,
      INTERACTION_RADIUS: 0.12,
      ENCOUNTER_INTERACTION_RADIUS: 0.19,
      COLLISION_RADIUS: 0.075,
      DOG_COLLISION_RADIUS: 0.065,
      SAFETY_GAP: 0.025,
      INITIAL: {
        living: { x: 0.72, y: 0.3 },
        kitchen: { x: 0.76, y: 0.58 },
        toilet: { x: 0.72, y: 0.3 },
      },
      HOTSPOT: {
        computer: { room: "living", x: 0.82, y: 0.2 },
        store: { room: "living", x: 0.16, y: 0.2 },
        clinic: { room: "living", x: 0.16, y: 0.34 },
      },
    },
    ECONOMY: {
      STARTER_MONEY: 12_000,
      MAX_INVENTORY: 99,
      STARTER_INVENTORY: {
        "food-basic": 3,
        "food-comfort": 0,
        "treat-basic": 6,
        "treat-mini": 0,
        "treat-lick": 0,
        "pad-paper": 3,
        "pad-absorbent": 0,
        "pad-wide": 0,
        "barrier-1-panel": 0,
        "barrier-2-panel": 0,
        "barrier-4-panel": 0,
        "shampoo-gentle": 1,
        "shampoo-quick": 0,
        "clinic-preventive": 0,
      },
      WORK: {
        BLOCK_MINUTES: 15,
        BLOCK_PROGRESS: 25,
        BASE_SALARY: 22_000,
        CONTINUITY_CARE_POINTS: 1,
        MAX_SALARY_BONUS_RATE: 0.45,
      },
      CATALOG: {
        "food-basic": {
          category: "food",
          label: "기본 사료",
          price: 3_000,
          effect: "배고픔을 안정적으로 낮춥니다.",
          unlockCarePoints: 0,
        },
        "food-comfort": {
          category: "food",
          label: "편안한 사료",
          price: 5_500,
          effect: "배고픔과 긴장을 함께 돌봅니다.",
          unlockCarePoints: 2,
        },
        "treat-basic": {
          category: "treat",
          label: "기본 간식",
          price: 1_500,
          effect: "정확한 타이밍의 보상에 사용합니다.",
          unlockCarePoints: 0,
        },
        "treat-mini": {
          category: "treat",
          label: "미니 간식",
          price: 2_200,
          effect: "짧은 반복 훈련에 알맞습니다.",
          unlockCarePoints: 2,
        },
        "treat-lick": {
          category: "treat",
          label: "핥기 간식",
          price: 3_800,
          effect: "차분한 후속 보상에 알맞습니다.",
          unlockCarePoints: 4,
        },
        "pad-paper": {
          category: "pad",
          label: "종이 패드",
          price: 1_800,
          effect: "작은 배변 구역을 만듭니다.",
          unlockCarePoints: 0,
          coverage: 0.12,
        },
        "pad-absorbent": {
          category: "pad",
          label: "흡수 패드",
          price: 3_200,
          effect: "조금 넓고 편안한 배변 구역을 만듭니다.",
          unlockCarePoints: 2,
          coverage: 0.18,
        },
        "pad-wide": {
          category: "pad",
          label: "와이드 패드",
          price: 5_400,
          effect: "넓은 배변 구역을 만듭니다.",
          unlockCarePoints: 5,
          coverage: 0.26,
        },
        "barrier-1-panel": {
          category: "barrier",
          label: "1패널 칸막이",
          price: 4_000,
          effect: "짧은 한 구간을 안전하게 나눕니다.",
          unlockCarePoints: 1,
          panels: 1,
        },
        "barrier-2-panel": {
          category: "barrier",
          label: "2패널 칸막이",
          price: 6_800,
          effect: "두 구간을 이어 행동 반경을 조절합니다.",
          unlockCarePoints: 3,
          panels: 2,
        },
        "barrier-4-panel": {
          category: "barrier",
          label: "4패널 칸막이",
          price: 10_500,
          effect: "충분한 면적의 안전 구역을 만듭니다.",
          unlockCarePoints: 6,
          panels: 4,
        },
        "shampoo-gentle": {
          category: "shampoo",
          label: "순한 샴푸",
          price: 3_500,
          effect: "차분하게 목욕을 마칩니다.",
          unlockCarePoints: 0,
        },
        "shampoo-quick": {
          category: "shampoo",
          label: "빠른 샴푸",
          price: 5_800,
          effect: "짧은 시간에 목욕을 마칩니다.",
          unlockCarePoints: 3,
        },
        "clinic-preventive": {
          category: "clinic",
          label: "접종·예방 관리 방문",
          price: 9_000,
          effect: "예방접종과 건강관리 일정을 기록합니다.",
          unlockCarePoints: 0,
        },
      },
      SALARY_UPGRADES: {
        "salary-routine": {
          label: "업무 루틴",
          carePointCost: 2,
          bonusRate: 0.15,
        },
        "salary-portfolio": {
          label: "포트폴리오",
          carePointCost: 4,
          bonusRate: 0.15,
        },
        "salary-specialist": {
          label: "전문 분야",
          carePointCost: 6,
          bonusRate: 0.15,
        },
      },
    },
    PLACEMENT: {
      MIN_COORDINATE: 0.04,
      MAX_COORDINATE: 0.96,
      MIN_BARRIER_SIZE: 0.08,
      MAX_BARRIER_SIZE: 0.72,
      MIN_ENCLOSURE_AREA: 0.2,
      DOORWAYS: {
        living: [
          { x: 0.9, y: 0.16, width: 0.1, height: 0.18 },
          { x: 0.9, y: 0.66, width: 0.1, height: 0.18 },
        ],
        kitchen: [{ x: 0, y: 0.62, width: 0.1, height: 0.2 }],
        toilet: [{ x: 0, y: 0.18, width: 0.1, height: 0.2 }],
      },
    },
  },
  PREDICTION: {
    BASE_CONFIDENCE: 20,
    QUEUE_CONFIDENCE: 30,
    SAMPLE_CONFIDENCE: 10,
    FALLBACK_START_MINUTES: 180,
    FALLBACK_END_MINUTES: 360,
  },
  W3: {
    RESOURCE_MIN: 0,
    RESOURCE_MAX: 100,
    INITIAL_OWNER_RESOURCES: {
      energy: 100,
      focus: 100,
      workScore: 100,
    },
    COST: {
      WALK_ENERGY: 18,
      INTERVENTION_ENERGY: 3,
      INTERVENTION_FOCUS: 2,
      INTERRUPT_WORK_SCORE: 15,
    },
  },
} as const;

export const ROOMS = ["living", "kitchen", "toilet"] as const;

export const SIGNALS = ["sniffFloor", "circle", "wander"] as const;
